= Пилипенко Егор
:table-caption!:

https://github.com/nao4j/cv/raw/master/Пилипенко%20Егор.pdf[Скачать актуальную версию в формате PDF]

[cols="5,3,2",frame=none,grid=none]
|===
|*Разработчик программного обеспечения* ^|yegor.pilipenko@gmail.com >|Москва, Россия
|===

== Ключевые навыки

Java, JUnit, Spring, Hibernate, RDBMS, MQ, Maven, Git, Работа в команде

== Опыт (5+ лет)

[cols="3,2,4",frame=none,grid=none]
|===
2+|*Сервис обмена большими файлами* >|АО "Синимекс-Информатика"

|NDA (Финтех) ^|2020 >|Электронный документооборот

3+|Java 8, Spring Boot 2, WildFly, Oracle, Kafka, Nginx, Ansible
|===

* Переписал "с нуля" и значительно упростил архитектуру сервиса для обмена большими файлами с использованием самых последних версий компонентов Spring, что позволило снизить затраты на его поддержку
* Написал Ansible Playbook для установки и обновления приложения в продакшене
* Реализовал Jenkins пайплайны для автоматизации сборки, статического анализа и тестирования кода приложения
* Реализовал Jenkins пайплайны для автоматизации деплоя приложения на тестовые стенды

[cols="3,2,4",frame=none,grid=none]
|===
2+|*Адаптер для обеспечения асинхронного взаимодействия с API Accellion* >|АО "Синимекс-Информатика"

|NDA (Финтех) ^|2019 >|Электронный документооборот

3+|Java 11, Spring Boot 2, MySQL, REST, Docker
|===

* Реализовал сервис-адаптер для конвертирования синхронного API Accellion в асинхронное, что позволило упростить работу с ним из асинхронной микросервисной системы
* Покрыл приложение End-To-End тестами
* Написал сопроводительную документацию для передачи сервиса команде проекта

[cols="3,2,4",frame=none,grid=none]
|===
2+|*Host-to-Host решение* >|АО "Синимекс-Информатика"

|NDA (Финтех) ^|2018 - 2021 >|Электронный документооборот

3+|Java 8, Spring Boot 1/2, PostgreSQL, IBM MQ, WildFly, ES & CQRS монолит, REST
|===

* Разработал большое количество новой функциональности для бэкенда сервера на Spring Boot 1 и клиента на Spring Boot 2 для обеспечения поддержки новых типов документов и каналов связи
* Спроектировал множество новых точек REST API и покрыл их тестами на Spring Test
* Написал веб-приложение на Spring Boot 2 и Thymeleaf для упрощения тестирования приложения через MQ
* Написал несколько эмуляторов внешних систем для обеспечения возможности тестирования приложений вне инфраструктуры заказчиков
* Поддерживал высокое покрытие проекта unit-тестами на Test-NG и JUnit 5
* Писал интеграционные тесты с применением Testcontainers
* Автоматизировал проверку кода приложения на уязвимости и информирование о них при помощи Jenkins Pipeline, что позволило команде устранять их еще до передачи кода на анализ отделу безопасности заказчика
* Самостоятельно спроектировал некоторые части системы
* Участвовал в экспертной и единоличной оценке трудозатрат на разработку новой функциональности
* Участвовал в кросс-ревью кода команды
* Внедрил использование FlywayDB для версионирования базы данных
* Участвовал в демонстрациях продукта для заказчиков
* Участвовал в поддержке приложений в продакшен средах заказчиков
* Обучал новых сотрудников основам разработки бэкенд приложений на Java и Spring Boot

[cols="3,2,4",frame=none,grid=none]
|===
2+|*Сервер интеграции с Национальным Расчетным Депозитарием* >|АО "Синимекс-Информатика"

|NDA (Финтех) ^|2016 - 2018 >|Электронный документооборот

3+|Java 6, Spring Framework 2, Wicket, XML, XSLT, Hibernate, MS SQL Server, Oracle
|===

* Разработал большое количество новой функциональности для legacy-бэкенда, что позволило заказчикам не вносить изменения во внутренние системы при обновлениях API НРД
* Разработал несколько новых компонентов для фронтенда, что позволило операторам заказчиков пользоваться новыми функциями бэкенда и упростило использование старых
* Значительно увеличил покрытие кода проекта unit-тестами
* Помог команде тестирования во внедрении End-To-End тестирования по методологии BDD на проекте с использованием Selenium и Cucumber и написал большое количество тестов
* Проанализировал возможные варианты решения проблемы с версионированием DB и внедрил Liquibase на проекте, а также провел семинар для коллег по его использованию

[cols="3,2,4",frame=none,grid=none]
|===
2+|*Desktop приложение для конфигурирования Oozie* >|ООО "Эй Ти Консалтинг"

|АО "Эй Ти Консалтинг" ^|2015 >|Инструменты для разработчиков

3+|Java 8, JavaFX, JAXB, TestFX
|===

* Проанализировал проблемы команды, поддающиеся автоматизации
* Разработал Desktop-приложение для упрощения конфигурирования Oozie, что позволило ускорить работу и снизить количество ошибок

[cols="3,2,4",frame=none,grid=none]
|===
2+|*Хранилище больших данных* >|ООО "Эй Ти Консалтинг"

|ПАО "Вымпелком" ^|2014 - 2016 >|Обработка больших данных

3+|Hadoop, MRUnit, Java 7, Oozie, Hive, Pig
|===

* Разработал множество map-reduce приложений на Hadoop, что позволило заказчику получать необходимые показатели из больших данных, которые ранее было возможно получить только из RDBMS на меньшем объеме
* Использовал методологию TDD применяя MRUnit, что позволило не задействовать мощности кластера и убедиться в корректности кода до первого запуска на реальном объеме данных
* Автоматизировал расчет необходимых агрегатов на кластере заказчика без участия человека используя Oozie
* Инициировал введение процедуры Code Review в отделе и проводил его на регулярной основе
* Проводил техническую часть собеседования новых сотрудников

== Образование

[cols="4,3,2",frame=none,grid=none]
|===
3+|*Математика. Компьютерные науки*

|Воронежский Государственный Университет |Факультет Компьютерных Наук >|2011 – 2015
|===

== Дополнительное образование

[cols="1,1",frame=none,grid=none]
|===
2+|https://otus.ru/certificate/fe126f9d86d74d4b899a424511b00b0f[*Разработчик на Spring Framework*]

|OTUS |2018
|===

[cols="1,1",frame=none,grid=none]
|===
2+|https://university.mongodb.com/course_completion/4c4587e4-fdd4-4bf9-9c61-34e32217?utm_source=copy&utm_medium=social&utm_campaign=university_social_sharing[*MongoDB Основы M001*]

|MongoDB University |2017
|===

[cols="1,1",frame=none,grid=none]
|===
2+|https://university.mongodb.com/course_completion/92283470-9ab1-4a81-91e3-b0c2c9ac?utm_source=copy&utm_medium=social&utm_campaign=university_social_sharing[*MongoDB для Java разработчиков M101J*]

|MongoDB University |2017
|===

[cols="1,1",frame=none,grid=none]
|===
2+|https://coursera.org/share/c4d9d863b2b43630ae592bb59853c208[*Погружение в Python*]

|Coursera |2017
|===

== Языки

* Русский – родной
* Английский – базовое владение

== Увлечения

* Программирование
* Автоматизированный дом
* Прогулки на велосипеде

== Ссылки

* https://t.me/nao4j[Telegram] @nao4j
* https://www.linkedin.com/in/nao4j[LinkedIn] /nao4j
* https://github.com/nao4j[GitHub] /nao4j
